# Generated by Django 4.2.5 on 2023-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='intro',
            field=models.CharField(max_length=200, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Name'),
        ),
    ]
