# Generated by Django 4.2.6 on 2023-11-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='c_article',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='c_text',
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='news.articles'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
