# Generated by Django 4.2.6 on 2023-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comments_options_rename_c_date_comments_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
