# Generated by Django 4.2.6 on 2023-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(blank=True, choices=[('R', 'Русский'), ('E', 'English')], max_length=1, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/main/img/avatars', verbose_name='Avatar'),
        ),
    ]
