# Generated by Django 4.2.6 on 2023-11-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_lang_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
